services:
  # Unified Metamorph Node (All-in-One)
  metamorph:
    build:
      context: .
      dockerfile: Dockerfile.metamorph
    ports:
      - "50051:50051"  # Ledger gRPC
      - "50052:50052"  # Engine gRPC
      - "8333:8333"    # P2P Network
    environment:
      - SERVICE_NAME=metamorph
      - NETWORK=main
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50051"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Individual Services (for development/testing)
  ledger:
    build:
      context: .
      dockerfile: Dockerfile.ledger
    ports:
      - "50061:50051"  # Different port to avoid conflict
    environment:
      - SERVICE_NAME=ledger
      - GRPC_PORT=50051
    profiles: ["individual"]

  engine:
    build:
      context: .
      dockerfile: Dockerfile.engine
    ports:
      - "50062:50052"  # Different port to avoid conflict
    environment:
      - SERVICE_NAME=engine
      - GRPC_PORT=50052
    profiles: ["individual"]

  conductor:
    build:
      context: .
      dockerfile: Dockerfile.conductor
    environment:
      - SERVICE_NAME=conductor
      - LEDGER_ADDR=ledger:50051
      - ENGINE_ADDR=engine:50052
    depends_on:
      - ledger
      - engine
    profiles: ["individual"]

  # Development tools
  grpcui:
    image: fullstorydev/grpcui:latest
    ports:
      - "8080:8080"
    command: ["-plaintext", "-bind", "0.0.0.0", "-port", "8080", "metamorph:50051"]
    depends_on:
      - metamorph

networks:
  default:
    name: metamorph-network
