---
# DigitalOcean Kubernetes UTXO Infrastructure
# Production-grade Bitcoin SV UTXO set management

apiVersion: v1
kind: Namespace
metadata:
  name: metamorph-utxo
  labels:
    app.kubernetes.io/name: metamorph-utxo
    app.kubernetes.io/component: blockchain-infrastructure

---
# Node Pool Labels and Taints Configuration
# Apply these to your DOKS cluster node pools:
#
# Data Pool (data-a): High-memory, SSD storage for UTXO database
# kubectl label nodes <node-name> node-type=data-a
# kubectl taint nodes <node-name> workload=data:NoSchedule
#
# Bus Pool (bus-a): High-throughput for message processing  
# kubectl label nodes <node-name> node-type=bus-a
# kubectl taint nodes <node-name> workload=bus:NoSchedule
#
# App Pool (app-a): General application workloads
# kubectl label nodes <node-name> node-type=app-a

---
# Scylla Operator for UTXO Storage
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scylla-operator
  namespace: metamorph-utxo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scylla-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["scylla.scylladb.com"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scylla-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scylla-operator
subjects:
- kind: ServiceAccount
  name: scylla-operator
  namespace: metamorph-utxo

---
# Scylla Cluster for UTXO Storage
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: metamorph-utxo-cluster
  namespace: metamorph-utxo
spec:
  version: 5.2.0
  agentVersion: 3.2.0
  developerMode: false
  cpuset: true
  automaticOrphanedNodeCleanup: true
  genericUpgrade:
    failureStrategy: Retry
    pollInterval: 10s
  datacenter:
    name: us-east-1
    racks:
    - name: rack-a
      scyllaConfig: "scylla-config"
      scyllaAgentConfig: "scylla-agent-config"
      members: 3
      storage:
        capacity: 500Gi
        storageClassName: do-block-storage-xfs
      resources:
        requests:
          cpu: 4
          memory: 16Gi
        limits:
          cpu: 8
          memory: 32Gi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: ["data-a"]
        tolerations:
        - key: workload
          operator: Equal
          value: data
          effect: NoSchedule

---
# Scylla Configuration for UTXO Optimization
apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-config
  namespace: metamorph-utxo
data:
  scylla.yaml: |
    cluster_name: 'Metamorph UTXO Cluster'
    num_tokens: 256
    hinted_handoff_enabled: true
    max_hint_window_in_ms: 10800000
    hinted_handoff_throttle_in_kb: 1024
    max_hints_delivery_threads: 2
    hints_flush_period_in_ms: 10000
    max_hints_file_size_in_mb: 128
    batchlog_replay_throttle_in_kb: 1024
    authenticator: AllowAllAuthenticator
    authorizer: AllowAllAuthorizer
    role_manager: CassandraRoleManager
    roles_validity_in_ms: 2000
    permissions_validity_in_ms: 2000
    credentials_validity_in_ms: 2000
    partitioner: org.apache.cassandra.dht.Murmur3Partitioner
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_segment_size_in_mb: 32
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider
        parameters:
          - seeds: "metamorph-utxo-cluster-us-east-1-rack-a-0.scylla.metamorph-utxo.svc.cluster.local"
    concurrent_reads: 32
    concurrent_writes: 32
    concurrent_counter_writes: 32
    memtable_allocation_type: heap_buffers
    index_summary_capacity_in_mb: 
    index_summary_resize_interval_in_minutes: 60
    trickle_fsync: false
    trickle_fsync_interval_in_kb: 10240
    storage_port: 7000
    ssl_storage_port: 7001
    listen_address: 
    start_native_transport: true
    native_transport_port: 9042
    start_rpc: false
    rpc_port: 9160
    rpc_keepalive: true
    rpc_server_type: sync
    thrift_framed_transport_size_in_mb: 15
    incremental_backups: false
    snapshot_before_compaction: false
    auto_snapshot: true
    tombstone_warn_threshold: 1000
    tombstone_failure_threshold: 100000
    column_index_size_in_kb: 64
    batch_size_warn_threshold_in_kb: 5
    batch_size_fail_threshold_in_kb: 50
    compaction_throughput_mb_per_sec: 16
    compaction_large_partition_warning_threshold_mb: 100
    sstable_preemptive_open_interval_in_mb: 50
    read_request_timeout_in_ms: 5000
    range_request_timeout_in_ms: 10000
    write_request_timeout_in_ms: 2000
    counter_write_request_timeout_in_ms: 5000
    cas_contention_timeout_in_ms: 1000
    truncate_request_timeout_in_ms: 60000
    request_timeout_in_ms: 10000
    cross_node_timeout: false
    endpoint_snitch: GossipingPropertyFileSnitch
    dynamic_snitch_update_interval_in_ms: 100
    dynamic_snitch_reset_interval_in_ms: 600000
    dynamic_snitch_badness_threshold: 0.1
    request_scheduler: org.apache.cassandra.scheduler.NoScheduler
    server_encryption_options:
      internode_encryption: none
      keystore: 
      keystore_password: 
      truststore: 
      truststore_password: 
    client_encryption_options:
      enabled: false
      optional: false
      keystore: 
      keystore_password: 
    internode_compression: dc
    inter_dc_tcp_nodelay: false
    tracetype_query_ttl: 86400
    tracetype_repair_ttl: 604800
    gc_warn_threshold_in_ms: 1000
    enable_user_defined_functions: false
    enable_scripted_user_defined_functions: false
    windows_timer_interval: 1

---
# Redpanda Cluster for High-Throughput Event Bus
apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-config
  namespace: metamorph-utxo
data:
  redpanda.yaml: |
    redpanda:
      data_directory: /var/lib/redpanda/data
      seed_servers:
        - host:
            address: redpanda-0.redpanda.metamorph-utxo.svc.cluster.local
            port: 33145
        - host:
            address: redpanda-1.redpanda.metamorph-utxo.svc.cluster.local
            port: 33145
        - host:
            address: redpanda-2.redpanda.metamorph-utxo.svc.cluster.local
            port: 33145
      rpc_server:
        address: 0.0.0.0
        port: 33145
      kafka_api:
        - address: 0.0.0.0
          port: 9092
      admin:
        - address: 0.0.0.0
          port: 9644
      developer_mode: false
    rpk:
      coredump_dir: /var/lib/redpanda/coredump
      tune_network: true
      tune_disk_scheduler: true
      tune_disk_nomerges: true
      tune_disk_write_cache: true
      tune_disk_irq: true
      tune_cpu: true
      tune_aio_events: true
      tune_clocksource: true
      tune_swappiness: true
    pandaproxy:
      pandaproxy_api:
        - address: 0.0.0.0
          port: 8082

---
# Redpanda StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: metamorph-utxo
spec:
  serviceName: redpanda
  replicas: 3
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values: ["bus-a"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["redpanda"]
            topologyKey: kubernetes.io/hostname
      tolerations:
      - key: workload
        operator: Equal
        value: bus
        effect: NoSchedule
      containers:
      - name: redpanda
        image: vectorized/redpanda:v23.2.5
        command:
        - /usr/bin/rpk
        - redpanda
        - start
        - --smp=2
        - --memory=4G
        - --reserve-memory=1G
        - --overprovisioned
        - --node-id=$(POD_NAME | sed 's/.*-//')
        - --check=false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9644
          name: admin
        - containerPort: 33145
          name: rpc
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/redpanda/data
        - name: config
          mountPath: /etc/redpanda
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
          limits:
            cpu: 2000m
            memory: 8Gi
      volumes:
      - name: config
        configMap:
          name: redpanda-config
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: do-block-storage-xfs
      resources:
        requests:
          storage: 100Gi

---
# Redpanda Service
apiVersion: v1
kind: Service
metadata:
  name: redpanda
  namespace: metamorph-utxo
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
  - name: admin
    port: 9644
    targetPort: 9644
  - name: rpc
    port: 33145
    targetPort: 33145

---
# KEDA ScaledObject for Event-Driven Scaling
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: metamorph-conductor-scaler
  namespace: metamorph-utxo
spec:
  scaleTargetRef:
    name: metamorph-conductor
  minReplicaCount: 2
  maxReplicaCount: 20
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda.metamorph-utxo.svc.cluster.local:9092
      consumerGroup: conductor-group
      topic: tx.validated.v1
      lagThreshold: '100'
      offsetResetPolicy: latest

---
# Enhanced Ledger Service with Scylla Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metamorph-ledger-scylla
  namespace: metamorph-utxo
  labels:
    app: metamorph
    component: ledger
    storage: scylla
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metamorph
      component: ledger
  template:
    metadata:
      labels:
        app: metamorph
        component: ledger
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-type
                operator: In
                values: ["app-a"]
      containers:
      - name: ledger
        image: golang:1.21-alpine
        command: ["/bin/sh"]
        args:
          - -c
          - |
            echo "ðŸ—„ï¸  Metamorph Ledger Service with Scylla UTXO Store"
            echo "ðŸ“Š Scylla Cluster: metamorph-utxo-cluster"
            echo "ðŸŒ Event Bus: Redpanda cluster"
            echo "âš¡ KEDA Scaling: Enabled"
            
            # Install dependencies
            apk add --no-cache git build-base
            
            # Create production ledger with Scylla backend
            cat > /tmp/ledger-scylla.go << 'EOF'
            package main
            
            import (
                "context"
                "fmt"
                "log"
                "net"
                "os"
                "time"
                
                "github.com/gocql/gocql"
                "google.golang.org/grpc"
                "google.golang.org/grpc/reflection"
            )
            
            type ScyllaUTXOStore struct {
                session *gocql.Session
            }
            
            func NewScyllaUTXOStore() (*ScyllaUTXOStore, error) {
                cluster := gocql.NewCluster("metamorph-utxo-cluster-us-east-1-rack-a-0.scylla.metamorph-utxo.svc.cluster.local")
                cluster.Keyspace = "metamorph"
                cluster.Consistency = gocql.Quorum
                cluster.Timeout = 5 * time.Second
                cluster.ConnectTimeout = 10 * time.Second
                
                session, err := cluster.CreateSession()
                if err != nil {
                    return nil, fmt.Errorf("failed to connect to Scylla: %v", err)
                }
                
                // Create keyspace and tables
                err = session.Query(`
                    CREATE KEYSPACE IF NOT EXISTS metamorph 
                    WITH REPLICATION = {
                        'class': 'SimpleStrategy',
                        'replication_factor': 3
                    }
                `).Exec()
                if err != nil {
                    log.Printf("Warning: Could not create keyspace: %v", err)
                }
                
                err = session.Query(`
                    CREATE TABLE IF NOT EXISTS metamorph.utxos (
                        txid blob,
                        vout int,
                        amount_sats bigint,
                        script_pubkey blob,
                        is_unspent boolean,
                        block_height bigint,
                        created_at timestamp,
                        PRIMARY KEY (txid, vout)
                    ) WITH CLUSTERING ORDER BY (vout ASC)
                `).Exec()
                if err != nil {
                    log.Printf("Warning: Could not create UTXO table: %v", err)
                }
                
                return &ScyllaUTXOStore{session: session}, nil
            }
            
            func main() {
                log.Println("ðŸš€ Starting Metamorph Ledger with Scylla UTXO Store")
                
                store, err := NewScyllaUTXOStore()
                if err != nil {
                    log.Printf("âš ï¸  Could not connect to Scylla, using in-memory store: %v", err)
                    // Fallback to in-memory for development
                    time.Sleep(30 * time.Second) // Keep container running
                    select {}
                }
                defer store.session.Close()
                
                log.Println("âœ… Connected to Scylla UTXO cluster")
                log.Println("ðŸ“Š UTXO table initialized")
                log.Println("ðŸŒ Starting gRPC server on :50051")
                
                lis, err := net.Listen("tcp", ":50051")
                if err != nil {
                    log.Fatalf("Failed to listen: %v", err)
                }
                
                s := grpc.NewServer()
                reflection.Register(s)
                
                log.Println("ðŸŽ¯ Ledger service ready for UTXO queries")
                if err := s.Serve(lis); err != nil {
                    log.Fatalf("Failed to serve: %v", err)
                }
            }
            EOF
            
            echo "ðŸ”§ Building Scylla-backed ledger service..."
            go mod init ledger-scylla
            go mod tidy
            go run /tmp/ledger-scylla.go
        env:
        - name: SCYLLA_HOSTS
          value: "metamorph-utxo-cluster-us-east-1-rack-a-0.scylla.metamorph-utxo.svc.cluster.local"
        - name: SCYLLA_KEYSPACE
          value: "metamorph"
        - name: LOG_LEVEL
          value: "info"
        ports:
        - containerPort: 50051
          name: grpc
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 10

---
# Ledger Service
apiVersion: v1
kind: Service
metadata:
  name: metamorph-ledger-scylla
  namespace: metamorph-utxo
spec:
  selector:
    app: metamorph
    component: ledger
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP

---
# HPA for Ledger Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: metamorph-ledger-hpa
  namespace: metamorph-utxo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metamorph-ledger-scylla
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# DigitalOcean Spaces Secret for Cold Storage
apiVersion: v1
kind: Secret
metadata:
  name: do-spaces-secret
  namespace: metamorph-utxo
type: Opaque
stringData:
  access-key: "your-spaces-access-key"
  secret-key: "your-spaces-secret-key"
  endpoint: "https://nyc3.digitaloceanspaces.com"
  bucket: "metamorph-blockchain-snapshots"

---
# Prometheus ServiceMonitor for SLO Monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metamorph-utxo-monitor
  namespace: metamorph-utxo
spec:
  selector:
    matchLabels:
      app: metamorph
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
