apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: verifier-keda
  namespace: metamorph-app
spec:
  scaleTargetRef: { name: verifier }
  pollingInterval: 5
  cooldownPeriod: 60
  minReplicaCount: 3
  maxReplicaCount: 500
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: redpanda-0:9092,redpanda-1:9092,redpanda-2:9092
      topic: p2p.raw_tx.v1
      consumerGroup: verifier-v1
      lagThreshold: "10000"
