apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: verifier-hpa
  namespace: metamorph-app
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: verifier }
  minReplicas: 3
  maxReplicas: 200
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: 70 } }
